[package]
name = "condr-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
atomicwrites.workspace = true
bincode.workspace = true
interprocess.workspace = true
condr-core = { path = "../condr-core" }
tokio.workspace = true

[target.'cfg(unix)'.dependencies]
nix.workspace = true

[target.'cfg(windows)'.dependencies]
widestring.workspace = true

[lints]
workspace = true
