[package]
name = "condr-gui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[[bin]]
name = "condr-gui"
path = "src/main.rs"

[features]
test-support = ["gpui-kit/test-support"]

[dependencies]
async-channel.workspace = true
gpui-kit.workspace = true
gpui-fps.workspace = true
image.workspace = true
condr-core = { path = "../condr-core" }
condr-server = { path = "../condr-server" }
serde.workspace = true
smol_str.workspace = true
toml.workspace = true
toml_edit.workspace = true

[target.'cfg(windows)'.dependencies]
windows-registry.workspace = true

[build-dependencies]
embed-resource.workspace = true

[dev-dependencies]
image = { workspace = true, features = ["ico"] }
resvg = { version = "0.46", default-features = false }

[lints]
workspace = true
