//! File-type icons for the Files sidebar and the Preview Tab (ADR 0018): the
//! material-icon-theme set (MIT, assets/icons/NOTICE-FILE-ICONS), looked up the way VS Code
//! does, by exact file name first and then by the longest dotted suffix. The tables and
//! the SVG bytes are generated by `script/generate-file-icons.mjs`.
//!
//! The icons are multi-colour, so they are drawn with `img()`, which rasterizes an SVG
//! as-is, not with `Icon`, which tints a silhouette in the text colour.

mod generated;

use std::path::Path;

const PREFIX: &str = "icons/material/";

/// The asset path of the icon for a file called `name`.
pub(super) fn file_icon(name: &str) -> String {
    let lower = name.to_ascii_lowercase();
    let icon = lookup(generated::FILE_NAMES, &lower)
        .or_else(|| {
            // `a.test.ts` tries `test.ts`, then `ts`: the longest known suffix wins.
            lower
                .match_indices('.')
                .find_map(|(index, _)| lookup(generated::FILE_EXTENSIONS, &lower[index + 1..]))
        })
        .unwrap_or("file");
    format!("{PREFIX}{icon}.svg")
}

/// The asset path of the icon for a directory called `name`.
pub(super) fn folder_icon(name: &str) -> String {
    let icon = lookup(generated::FOLDER_NAMES, &name.to_ascii_lowercase()).unwrap_or("folder");
    format!("{PREFIX}{icon}.svg")
}

/// The icon for the last component of `path`, a file.
pub(super) fn file_icon_for_path(path: &Path) -> String {
    file_icon(
        path.file_name()
            .and_then(|name| name.to_str())
            .unwrap_or_default(),
    )
}

/// The bytes behind one of this module's asset paths, for the asset source.
pub(crate) fn icon_bytes(path: &str) -> Option<&'static [u8]> {
    let icon = path.strip_prefix(PREFIX)?.strip_suffix(".svg")?;
    lookup(generated::ICONS, icon)
}

/// Every asset path this module serves, for the asset source's listing.
pub(crate) fn icon_paths() -> impl Iterator<Item = String> {
    generated::ICONS
        .iter()
        .map(|(icon, _)| format!("{PREFIX}{icon}.svg"))
}

fn lookup<T: Copy>(table: &'static [(&'static str, T)], key: &str) -> Option<T> {
    table
        .binary_search_by(|(candidate, _)| candidate.cmp(&key))
        .ok()
        .map(|index| table[index].1)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_tables_are_sorted_for_binary_search() {
        for table in [
            generated::FILE_NAMES,
            generated::FILE_EXTENSIONS,
            generated::FOLDER_NAMES,
        ] {
            assert!(table.windows(2).all(|pair| pair[0].0 < pair[1].0));
        }
        assert!(
            generated::ICONS
                .windows(2)
                .all(|pair| pair[0].0 < pair[1].0)
        );
    }

    #[test]
    fn every_mapped_icon_exists_and_resolves_through_the_asset_path() {
        for (_, icon) in generated::FILE_NAMES
            .iter()
            .chain(generated::FILE_EXTENSIONS)
            .chain(generated::FOLDER_NAMES)
        {
            let path = format!("{PREFIX}{icon}.svg");
            assert!(icon_bytes(&path).is_some(), "{icon} has no SVG");
        }
        assert!(icon_bytes("icons/material/file.svg").is_some());
        assert!(icon_bytes("icons/material/folder.svg").is_some());
        assert!(icon_bytes("icons/circle.svg").is_none());
    }

    #[test]
    fn files_resolve_by_name_then_longest_suffix_then_default() {
        assert_eq!(file_icon("main.rs"), "icons/material/rust.svg");
        assert_eq!(file_icon("Main.RS"), "icons/material/rust.svg");
        assert_eq!(file_icon("README.md"), "icons/material/readme.svg");
        assert_eq!(file_icon("Dockerfile"), "icons/material/docker.svg");
        assert_eq!(
            file_icon("app.test.ts"),
            "icons/material/test-ts.svg",
            "the longer suffix beats the plain extension"
        );
        assert_eq!(file_icon("types.d.ts"), "icons/material/typescript-def.svg");
        assert_eq!(file_icon("no-extension"), "icons/material/file.svg");
        assert_eq!(file_icon("weird.zzzz"), "icons/material/file.svg");
        assert_eq!(
            file_icon_for_path(Path::new("crates/gui/Cargo.toml")),
            file_icon("Cargo.toml")
        );
    }

    #[test]
    fn folders_resolve_by_name_then_default() {
        assert_eq!(folder_icon("src"), "icons/material/folder-src.svg");
        assert_eq!(folder_icon("SRC"), "icons/material/folder-src.svg");
        assert_eq!(folder_icon("docs"), "icons/material/folder-docs.svg");
        assert_eq!(folder_icon("mystery"), "icons/material/folder.svg");
    }
}
