// condr agent-hook opencode — generated by condr, do not edit.
import { spawn } from "node:child_process"

export default {
  id: "condr.agent-status",
  tui: async (api) => {
    if (process.env.CONDR_ENV !== "1") return
    const exe = __CONDR_EXECUTABLE__
    const report = (event, id) => new Promise((resolve) => {
      const child = spawn(exe, ["agent-hook", "opencode", event], {
        stdio: ["pipe", "ignore", "ignore"], timeout: 2000,
      })
      child.on("error", () => resolve(false))
      child.on("close", (code) => resolve(code === 0))
      child.stdin.on("error", () => {})
      child.stdin.end(JSON.stringify({ session_id: id }))
    })
    let selected, last, reportedAt = 0, running = false, disposed = false
    const tick = async () => {
      if (running || disposed) return
      running = true
      try {
        const route = api.route.current
        const id = route.name === "session" ? route.params?.sessionID : undefined
        const session = id && api.state.session.get(id)
        if (!session || session.parentID) return
        if (selected !== id) {
          if (!await report("session-start", id)) return
          selected = id
          last = undefined
        }
        const status = api.state.session.status(id)?.type
        const event = api.state.session.permission(id).length ? "permission-request"
          : api.state.session.question(id).length ? "question-asked"
          : status === "busy" || status === "retry" ? "prompt-submit"
          : status === "idle" ? "stop" : undefined
        // A hook can precede process discovery. A sparse heartbeat also recovers that
        // first report without queuing work or blocking the TUI on child processes.
        if (event && (event !== last || Date.now() - reportedAt >= 5000)) {
          if (await report(event, id)) {
            last = event
            reportedAt = Date.now()
          }
        }
      } catch {
        // Hook failures must not interrupt the native CLI.
      } finally {
        running = false
      }
    }
    const timer = setInterval(tick, 100)
    api.lifecycle.onDispose(() => { disposed = true; clearInterval(timer) })
    await tick()
  },
}
