[package]
name = "murmur-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
bincode.workspace = true
interprocess.workspace = true
murmur-core = { path = "../murmur-core" }
tokio.workspace = true

[target.'cfg(windows)'.dependencies]
widestring.workspace = true

[lints]
workspace = true
