[package]
name = "murmur-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
alacritty_terminal.workspace = true
bincode.workspace = true
portable-pty.workspace = true
serde.workspace = true
sysinfo.workspace = true

[target.'cfg(unix)'.dependencies]
nix.workspace = true

[lints]
workspace = true
